apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "NVIDIA GPU Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: nvidia-gpu-operator
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "20" # Use a higher weight to ensure it runs after other critical operators
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    # Add any specific labels required by NVIDIA GPU operator or for monitoring
    # openshift.io/cluster-monitoring: 'true'
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gpu-operator-certified
  namespace: nvidia-gpu-operator
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "21"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  targetNamespaces:
    - nvidia-gpu-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gpu-operator-certified
  namespace: nvidia-gpu-operator
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "22"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  installPlanApproval: Automatic
  name: gpu-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace