apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Red Hat OpenShift AI"
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "10" # Use a higher weight to allow NFD to go first, if desired
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: redhat-ods-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "11"
    helm.sh/hook-delete-policy: before-hook-creation
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "12"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  name: rhods-operator
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic